### ISSUE TITLE
NullPointerException will be thrown if defined custom scope and factories

### ISSUE THREAD

**Issue by freewind** [adamw/macwire#39]
```scala
package my

import com.softwaremill.macwire.Macwire
import com.softwaremill.macwire.scopes.{ProxyingScope, Scope}

import scala.collection.mutable

class Group {
  def helloGroup(): Unit = {
    println("Hello group")
  }
}

object UserServiceFactory {
  type UserService = UserServiceFactory#create
}

class UserServiceFactory(group: Group) {
  case class create() {
    def helloService() = group.helloGroup()
  }
}

class User(userServiceFactory: UserServiceFactory) {
  def helloUser() = userServiceFactory.create().helloService()
}

trait Module extends Macwire {
  lazy val group = projectScope(wire[Group])
  lazy val userServiceFactory = projectScope(wire[UserServiceFactory])
  lazy val user = projectScope(wire[User])
  def projectScope: Scope = new ProjectScope
}

class ProjectScope extends ProxyingScope {
  private val map = mutable.HashMap[String, Any]()
  override def get[T](key: String, createT: => T): T = {
    map.get(key) match {
      case Some(v) => v.asInstanceOf[T]
      case _ => val v = createT
        map.put(key, v)
        v
    }
  }
}

object Main extends App with Module {
  user.helloUser()
}

```

When run it, it will throw exception:

```
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at com.softwaremill.macwire.scopes.ProxyingScope$$anon$1.invoke(ProxyingScope.scala:16)
	at my.User_$$_jvst16_0.helloUser(User_$$_jvst16_0.java)
	at my.Main$.delayedEndpoint$my$Main$1(User.scala:48)
	at my.Main$delayedInit$body.apply(User.scala:47)
	at scala.Function0$class.apply$mcV$sp(Function0.scala:40)
	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
	at scala.App$$anonfun$main$1.apply(App.scala:76)
	at scala.App$$anonfun$main$1.apply(App.scala:76)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:35)
	at scala.App$class.main(App.scala:76)
	at my.Main$.main(User.scala:47)
	at my.Main.main(User.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:134)
Caused by: java.lang.NullPointerException
	at my.UserServiceFactory$create.helloService(User.scala:20)
	at my.User.helloUser(User.scala:25)
	... 22 more
```

One way to fix it, is to add `val` to parameters of the factories:

```scala
class UserServiceFactory(val group: Group) 
class User(val userServiceFactory: UserServiceFactory) 
```

Any thoughts?

**Comment by adamw** [comment]
It seems that there's a problem when using both proxies and nested-case classes. I don't think it's a problem with MacWire itself, rather some interaction between the way nested case classes are compiled and the dynamic proxying mechanism from java.

However, I think factories can be better expressed using methods inside modules or plain methods inside classes - and that also solves the NPE problem.

**Comment by freewind** [comment]
Could you give me one example?

I use the `case class create` approach because I saw an article recommended that, not sure if there is any other better solution?

**Comment by adamw** [comment]
Yes, the approach with the case classes was kind of an expirment, it works for some cases but overall the code can end up being confusing. Take a look here: http://di-in-scala.github.io/#factories there are two examples on how to create factories

**Comment by freewind** [comment]
@adamw thanks for the link, but I couldn't understand the second example well:

```scala
trait StationModule {
      def trainStation(name: Name) = wire[TrainStation]

      lazy val trainDispatch = wire[TrainDispatch]

      // dependencies of the module
      def trainShunter: TrainShunter 
      def trainLoader: TrainLoader
}
```

We defined a factory method `trainStation` in a trait, but how can I use it as a dependency in other classes?

Say I have another class which want the factory to create a `trainStation`:

```scala
class City(val trainShunter: TrainShunter, val trainLoader: TrainLoader) extends StationModule {
    val traintStation1 = trainStation(name1)
    val traintStation2 = trainStation(name2)
}
```

What should I put in the `???` part? Does the `City` class need to extends the `StationModule` trait, like:

```scala
class City(trainStationFactory: ???) {
    val traintStation1 = trainStationFactory.apply(name1)
    val traintStation2 = trainStationFactory.apply(name2)
}
```

**Comment by adamw** [comment]
So here I would rather use the first approach. Modules should only be extended when you wire the whole application, not by individual classes. That is, define a type of your factory and a value:

````scala
package object my.package { // or anywhere else where the definition will be visible
   type TrainStationFactory = Name => TrainStation
}
trait StationModule {
   val trainStation = (name: Name) => wire[TrainStation]
}

class City(..., tsf: TrainStationFactory) {
   val trainStation1 = tsf(name1)
}

**Comment by freewind** [comment]
Thanks, so we can just define a function, it's also a very good approach
